[workspace]
members = ["cli", "core", "web"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.48", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
